source "https://rubygems.org"  # where gems will be downloaded from
ruby "~> 3.0.0"  # ruby version, change for the one you use

gem "httparty"
gem "dotenv" # needed for work with .env files
gem "nokogiri" # used by reverse_markdown
gem "reverse_markdown"  # to convert html to markdown
